In [14]:
import pandas as pd
pd.set_option('display.float_format', '{:,.1f}'.format)  # 숫자 천단위 콤마

In [15]:
df = pd.read_csv('pandas/data/computer_prices_all.csv')
df.head(10)

,device_type,brand,model,release_year,os,form_factor,cpu_brand,cpu_model,cpu_tier,cpu_cores,...,resolution,refresh_hz,battery_wh,charger_watts,psu_watts,wifi,bluetooth,weight_kg,warranty_months,price
0,Desktop,Samsung,Samsung Forge XDI,2022,Windows,ATX,Intel,Intel i5-11129,3,12,...,2560x1440,90,0,0,750,Wi-Fi 6,5.1,11.0,36,"1,384.0"
1,Laptop,Samsung,Samsung Pro KM8,2022,Windows,Mainstream,Intel,Intel i7-11114,4,12,...,1920x1080,90,56,120,0,Wi-Fi 6,5.3,2.0,12,"2,275.0"
2,Desktop,Lenovo,Lenovo Strix BIE,2024,macOS,SFF,AMD,AMD Ryzen 5 5168,2,8,...,3440x1440,120,0,0,850,Wi-Fi 6,5.0,7.0,24,"1,880.0"
3,Desktop,Dell,Dell Cube AXR,2024,Windows,ATX,AMD,AMD Ryzen 5 7550,2,6,...,3440x1440,120,0,0,650,Wi-Fi 6,5.2,6.0,36,"1,332.0"
4,Laptop,Gigabyte,Gigabyte Pro IX1,2024,Linux,Gaming,AMD,AMD Ryzen 7 6230,5,16,...,2560x1600,90,80,90,0,Wi-Fi 6,5.2,1.5,12,"2,682.0"
5,Desktop,MSI,MSI Think KSG,2025,Windows,ATX,Intel,Intel i7-10369,5,16,...,2560x1440,90,0,0,1000,Wi-Fi 5,5.0,9.0,36,"2,752.0"
6,Desktop,Apple,Apple Arena R5Q,2024,Windows,ATX,Apple,Apple M2,2,6,...,2560x1440,60,0,0,850,Wi-Fi 6,5.1,9.0,24,"1,610.0"
7,Desktop,Apple,Apple Station EWP,2023,Windows,Micro-ATX,Apple,Apple M2 Pro,3,8,...,2560x1440,60,0,0,650,Wi-Fi 6,5.0,8.0,12,"2,140.0"
8,Laptop,Dell,Dell Creator GIQ,2024,Windows,Mainstream,Intel,Intel i9-14473,6,26,...,2560x1600,60,80,240,0,Wi-Fi 5,5.0,1.2,48,"2,954.0"
9,Laptop,Lenovo,Lenovo Blade MIZ,2025,Windows,Ultrabook,AMD,AMD Ryzen 3 4374,1,4,...,3840x2160,120,60,45,0,Wi-Fi 6,5.3,1.5,24,"1,654.0"

In [16]:
df.describe(include='all')

,device_type,brand,model,release_year,os,form_factor,cpu_brand,cpu_model,cpu_tier,cpu_cores,...,resolution,refresh_hz,battery_wh,charger_watts,psu_watts,wifi,bluetooth,weight_kg,warranty_months,price
count,100000,100000,100000,"100,000.0",100000,100000,100000,100000,"100,000.0","100,000.0",...,100000,"100,000.0","100,000.0","100,000.0","100,000.0",100000,"100,000.0","100,000.0","100,000.0","100,000.0"
unique,2,10,99036,NaN,4,10,3,26971,NaN,NaN,...,6,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN
top,Laptop,Lenovo,Lenovo Think 0V5,NaN,Windows,Mainstream,Intel,Apple M2 Pro,NaN,NaN,...,1920x1080,NaN,NaN,NaN,NaN,Wi-Fi 6,NaN,NaN,NaN,NaN
freq,59844,15992,3,NaN,71817,17819,52774,1389,NaN,NaN,...,47993,NaN,NaN,NaN,NaN,46149,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,"2,022.3",NaN,NaN,NaN,NaN,3.2,10.5,...,NaN,98.5,41.8,61.4,272.5,NaN,5.1,4.3,22.2,"1,928.8"
std,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,1.4,5.0,...,NaN,43.3,35.9,62.8,354.7,NaN,0.2,3.8,10.2,580.5
min,NaN,NaN,NaN,"2,018.0",NaN,NaN,NaN,NaN,1.0,4.0,...,NaN,60.0,0.0,0.0,0.0,NaN,4.2,0.9,12.0,373.0
25%,NaN,NaN,NaN,"2,021.0",NaN,NaN,NaN,NaN,2.0,6.0,...,NaN,60.0,0.0,0.0,0.0,NaN,5.0,1.5,12.0,"1,504.0"
50%,NaN,NaN,NaN,"2,023.0",NaN,NaN,NaN,NaN,3.0,8.0,...,NaN,90.0,56.0,65.0,0.0,NaN,5.1,2.0,24.0,"1,864.0"
75%,NaN,NaN,NaN,"2,024.0",NaN,NaN,NaN,NaN,4.0,14.0,...,NaN,120.0,70.0,90.0,650.0,NaN,5.2,7.0,24.0,"2,288.0"
max,NaN,NaN,NaN,"2,025.0",NaN,NaN,NaN,NaN,6.0,28.0,...,NaN,240.0,99.0,240.0,"1,200.0",NaN,5.3,16.0,48.0,"10,985.0"

In [17]:
# device type 고유값
print(f"Device Type: {df['device_type'].nunique()}개")
print(df['device_type'].unique())

print()

# brand 고유값
print(f"Brand: {df['brand'].nunique()}개")
print(df['brand'].unique())

Device Type: 2개
['Desktop' 'Laptop']

Brand: 10개
['Samsung' 'Lenovo' 'Dell' 'Gigabyte' 'MSI' 'Apple' 'HP' 'Acer' 'ASUS'
 'Razer']

In [18]:
# 브랜드별 데이터 개수 확인
df['brand'].value_counts()

brand
Lenovo      15992
HP          14114
Dell        14005
Apple       11915
ASUS        10159
Acer         9925
Samsung      8066
MSI          7891
Gigabyte     4900
Razer        3033
Name: count, dtype: int64

In [19]:
group = df.groupby(by='brand')
print(group)
print(f'그룹수: {group.ngroups}')
print(f'그룹 데이터: {group.groups.keys()}')

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x168dd7b10>
그룹수: 10
그룹 데이터: dict_keys(['ASUS', 'Acer', 'Apple', 'Dell', 'Gigabyte', 'HP', 'Lenovo', 'MSI', 'Razer', 'Samsung'])

In [22]:
for key, val in group:
    print(f'{key}:{len(val)}')
    print()

ASUS:10159

Acer:9925

Apple:11915

Dell:14005

Gigabyte:4900

HP:14114

Lenovo:15992

MSI:7891

Razer:3033

Samsung:8066